baseURL = "https://gerdi.netlify.app/"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Gerdis Ferienwohnung"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Home"
languageCode = "de-de"
languageName = "De"
weight = 1
[Languages.fr]
contentDir = ""
copyright = ""
home = ""
languageCode = ""
languageName = ""
weight = ""
[menu]
footer = []
[[menu.main]]
URL = "about"
name = "Über uns"
weight = 1
[[menu.main]]
URL = "project"
name = "Bilder"
weight = 2
[[menu.main]]
URL = "service"
name = "Freizeitangebote"
weight = 3
[[menu.main]]
URL = "pricing"
name = "Preise"
parent = "Pages"
weight = "4"
[[menu.main]]
URL = "contact"
name = "Kontakt"
weight = 6
[[menu.main]]
URL = "faq"
name = "Impressum"
parent = "Pages"
weight = "7"
[params]
author = "Themefisher"
contact_form_action = "#"
description = "Gerdis Ferienwohnung Test"
email = "gerdi@email.com"
google_analitycs_id = ""
location = "Ränkam,Bayern"
logo = "/images/living-on-the-edge-844873_640.jpg"
mobile = "0123456789"
multi_author = false
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
